export default {
    supplier: 'Mobarak',
    divisions: [],
    permanentDistricts: [],
    districts: [],
    upazilas: [],
    permanentUpazilas: [],
    sameAddress: false,
    currentDivisionId: null,
    permanentDivisionId: null,
    currentDistrictId: null,
    permanentDistrictId: null,
    currentUpazilaId: null,
    permanentUpazilaId: null,
    branches: [],
    branchId: null,
    areas: [],
    areaId: null,
    permanent_village: null,
    permanent_post_office: null,
    village: null,
    post_office: null,
    fdr_amount: null,
}
